/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "asociacion.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

State *
ponerasociacion_1(datos_nueva_asociacion *argp, CLIENT *clnt)
{
	static State clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ponerAsociacion,
		(xdrproc_t) xdr_datos_nueva_asociacion, (caddr_t) argp,
		(xdrproc_t) xdr_State, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ResultElemento *
obtenerasociacion_1(datos_asociacion *argp, CLIENT *clnt)
{
	static ResultElemento clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtenerAsociacion,
		(xdrproc_t) xdr_datos_asociacion, (caddr_t) argp,
		(xdrproc_t) xdr_ResultElemento, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

State *
borrarasociacion_1(datos_asociacion *argp, CLIENT *clnt)
{
	static State clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, borrarAsociacion,
		(xdrproc_t) xdr_datos_asociacion, (caddr_t) argp,
		(xdrproc_t) xdr_State, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ResultLista *
enumerar_1(ID *argp, CLIENT *clnt)
{
	static ResultLista clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, enumerar,
		(xdrproc_t) xdr_ID, (caddr_t) argp,
		(xdrproc_t) xdr_ResultLista, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
