/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dns.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_STRING))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_machine (XDR *xdrs, machine *objp)
{
	register int32_t *buf;

	 if (!xdr_str_t (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_str_t (xdrs, &objp->net))
		 return FALSE;
	 if (!xdr_str_t (xdrs, &objp->ip))
		 return FALSE;
	return TRUE;
}
