/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dns.h"

void
dnsprog_1(char *host, machine maquina)
{
	CLIENT *clnt;
	char *  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, DNSPROG, DNSVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	result_1 = dns1_1(&maquina, clnt);
	if (result_1 == (str_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Resultado: %s\n",*result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	machine maquina;

	if (argc < 4) {
		printf ("usage: %s server_host machine net\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	maquina.name = argv[2];
	maquina.net = argv[3];
	
	printf("--SIMULADOR DNS--");
	
	printf("\n\nNombre de la maquina: %s", maquina.name);
	printf("\n\nRed de la maquina: %s", maquina.net);
	
	dnsprog_1 (host, maquina);
	exit (0);
}
