/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "asociacion.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
listaasociaciones_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datos_nueva_asociacion ponerasociacion_1_arg;
		datos_asociacion obtenerasociacion_1_arg;
		datos_asociacion borrarasociacion_1_arg;
		ID enumerar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ponerAsociacion:
		_xdr_argument = (xdrproc_t) xdr_datos_nueva_asociacion;
		_xdr_result = (xdrproc_t) xdr_State;
		local = (char *(*)(char *, struct svc_req *)) ponerasociacion_1_svc;
		break;

	case obtenerAsociacion:
		_xdr_argument = (xdrproc_t) xdr_datos_asociacion;
		_xdr_result = (xdrproc_t) xdr_ResultElemento;
		local = (char *(*)(char *, struct svc_req *)) obtenerasociacion_1_svc;
		break;

	case borrarAsociacion:
		_xdr_argument = (xdrproc_t) xdr_datos_asociacion;
		_xdr_result = (xdrproc_t) xdr_State;
		local = (char *(*)(char *, struct svc_req *)) borrarasociacion_1_svc;
		break;

	case enumerar:
		_xdr_argument = (xdrproc_t) xdr_ID;
		_xdr_result = (xdrproc_t) xdr_ResultLista;
		local = (char *(*)(char *, struct svc_req *)) enumerar_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (LISTAASOCIACIONES, LISTA_ASOCIACIONES_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, LISTAASOCIACIONES, LISTA_ASOCIACIONES_VERSION, listaasociaciones_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (LISTAASOCIACIONES, LISTA_ASOCIACIONES_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, LISTAASOCIACIONES, LISTA_ASOCIACIONES_VERSION, listaasociaciones_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (LISTAASOCIACIONES, LISTA_ASOCIACIONES_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
