/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dns.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
dnsprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		machine dns1_1_arg;
		machine dns1rename_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case DNS1:
		_xdr_argument = (xdrproc_t) xdr_machine;
		_xdr_result = (xdrproc_t) xdr_str_t;
		local = (char *(*)(char *, struct svc_req *)) dns1_1_svc;
		break;

	case DNS1rename:
		_xdr_argument = (xdrproc_t) xdr_machine;
		_xdr_result = (xdrproc_t) xdr_str_t;
		local = (char *(*)(char *, struct svc_req *)) dns1rename_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
dnsprog2_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		machine dns2_1_arg;
		machine dns2rename_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case DNS2:
		_xdr_argument = (xdrproc_t) xdr_machine;
		_xdr_result = (xdrproc_t) xdr_str_t;
		local = (char *(*)(char *, struct svc_req *)) dns2_1_svc;
		break;

	case DNS2rename:
		_xdr_argument = (xdrproc_t) xdr_machine;
		_xdr_result = (xdrproc_t) xdr_str_t;
		local = (char *(*)(char *, struct svc_req *)) dns2rename_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DNSPROG, DNSVERS);
	pmap_unset (DNSPROG2, DNSVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DNSPROG, DNSVERS, dnsprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DNSPROG, DNSVERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, DNSPROG2, DNSVERS, dnsprog2_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DNSPROG2, DNSVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DNSPROG, DNSVERS, dnsprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DNSPROG, DNSVERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, DNSPROG2, DNSVERS, dnsprog2_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DNSPROG2, DNSVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
