/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dns.h"

void
dnsprog_1(char *host, machine maquina)
{
	CLIENT *clnt;
	char *  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, DNSPROG, DNSVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	if( maquina.ip == NULL ) {		// Si no se ha especificado ninguna ip asumimos que el usuario está buscándola
		result_1 = dns1_1(&maquina, clnt);		
	} else {				// En caso contrario asumimos que el usuario quiere insertar o renombrar el dispositivo
		result_1 = dns1rename_1(&maquina, clnt);
	}

	if (result_1 == (str_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Resultado: %s\n",*result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	machine maquina;

	if (argc < 4) {
		printf ("usage: %s server_host machine net ip[rename]\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	maquina.name = argv[2];		// Nombre del dispositivo
	maquina.net = argv[3];		// Red en la que se encuentra

	if (argc == 5) {		// Guardamos la ip si se ha enviado para renombrar
		maquina.ip = argv[4];
	}
	
	printf("--SIMULADOR DNS--");
	
	printf("\n\nNombre de la maquina: %s", maquina.name);
	printf("\n\nRed de la maquina: %s", maquina.net);
	
	dnsprog_1 (host, maquina);
	exit (0);
}
